name: flutter_a
packageName: flutter_app
description: A new Flutter project.
buildNumber: 12212

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  sliding_up_panel: ^0.3.6
  flutter_speed_dial: ^1.2.5
  fluro: "^1.5.1" # 路由插件
  rxdart: ^0.22.0
  package_info: ^0.4.0+2 # 获取APP包的信息
  connectivity: ^0.4.2 # 判断手机当前网络状况
  dio: ^3.0.8 #请求
  # flutter_i18n: ^0.6.3 #国际化
  shared_preferences: ^0.5.3+4 #localstorage存储
  flutter_swiper: ^1.1.6 #轮播图
  path_provider: ^1.5.1 #本地文件读取
  cached_network_image: ^2.0.0 #缓存图片
  # webview_flutter: ^0.3.19+5 #webview 
  # 使用最新版webviewflutter有可能会报错
  #   Xcode's output:
  # ↳
  #     warning: Capabilities for Runner may not function correctly because its entitlements use a placeholder team ID. To resolve this, select a development team in the build settings editor. (in target 'Runner')
  #     /Users/yangxuhui/work/flutter/.pub-cache/hosted/pub.flutter-io.cn/webview_flutter-0.3.19+5/ios/Classes/FlutterWebView.m:105:29: error: property 'automaticallyAdjustsScrollIndicatorInsets' not found on object of type 'UIScrollView *'
  #             _webView.scrollView.automaticallyAdjustsScrollIndicatorInsets = NO; 
  # 原因 大概是XCode不支持ios13时，就会发生这种情况。该插件有ios13的代码，但较早的xcode版本无法识别这些命令，因此会引发错误。我的xcode版本为10.3,升级系统版本和XCode版本风险太大不可控，决定切换 flutter_webview_plugin: ^0.3.10+1
  flutter_webview_plugin: ^0.3.10+1 #webview
  flutter_easyrefresh: ^2.0.8
  flutter_spinkit: "^4.1.1"
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/image/boot/boot_1.jpg
    - assets/image/boot/boot_2.jpg
    - assets/image/boot/boot_3.jpg
    - assets/image/boot/boot_4.jpg
    - assets/image/boot/2.0x/boot_1.jpg
    - assets/image/boot/2.0x/boot_2.jpg
    - assets/image/boot/2.0x/boot_3.jpg
    - assets/image/boot/2.0x/boot_4.jpg
    - assets/image/boot/3.0x/boot_1.jpg
    - assets/image/boot/3.0x/boot_2.jpg
    - assets/image/boot/3.0x/boot_3.jpg
    - assets/image/boot/3.0x/boot_4.jpg
    - assets/image/splash/splash.jpg
    - assets/image/splash/2.0x/splash.jpg
    - assets/image/splash/3.0x/splash.jpg
    - assets/image/icon/a_0.png
    - assets/image/icon/a_1.png
    - assets/image/icon/b_0.png
    - assets/image/icon/b_1.png
    - assets/image/icon/c_0.png
    - assets/image/icon/c_1.png
    - assets/image/icon/d_0.png
    - assets/image/icon/d_1.png
    - assets/image/icon/2.0x/a_0.png
    - assets/image/icon/2.0x/a_1.png
    - assets/image/icon/2.0x/b_0.png
    - assets/image/icon/2.0x/b_1.png
    - assets/image/icon/2.0x/c_0.png
    - assets/image/icon/2.0x/c_1.png
    - assets/image/icon/2.0x/d_0.png
    - assets/image/icon/2.0x/d_1.png
    - assets/image/icon/3.0x/a_0.png
    - assets/image/icon/3.0x/a_1.png
    - assets/image/icon/3.0x/b_0.png
    - assets/image/icon/3.0x/b_1.png
    - assets/image/icon/3.0x/c_0.png
    - assets/image/icon/3.0x/c_1.png
    - assets/image/icon/3.0x/d_0.png
    - assets/image/icon/3.0x/d_1.png
    - assets/image/public/placeholder.jpg
    - assets/image/public/error.jpg
    - assets/image/public/2.0x/placeholder.jpg
    - assets/image/public/2.0x/error.jpg
    - assets/image/public/3.0x/placeholder.jpg
    - assets/image/public/3.0x/error.jpg
    - assets/image/public/logo.png
    - assets/image/public/2.0x/logo.png
    - assets/image/public/3.0x/logo.png
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
